language: node_js
node_js:
  - 10.15.0
cache:
  directories:
    - ~/.cache
install:
  - yarn install --frozen-lockfile
before_script:
  - yarn start & yarn run wait-on http://localhost:3000
script:
  - yarn test
  - yarn run cypress run --record --key 71815344-d092-46ef-8290-e80eeab2ccff
  - kill $(jobs -p) || true
