language: node_js
node_js:
  - 10.15.0
env:
  - TRAVIS_REPO_SLUG=JIB-8352/chatham_smart_map
cache:
  directories:
    - ~/.cache
install:
  - yarn install --frozen-lockfile
  - yarn build
before_script:
  - yarn start & yarn run wait-on http://localhost:3000
script:
  - yarn test
  - yarn run cypress run --record --key f22f3805-daeb-4d67-a238-d0a50b15d629 --browser chrome
  - kill $(jobs -p) || true
