language: node_js
node_js:
  - 10.15.0
cache:
  directories:
    - node_modules

before_script:
  - yarn build
  - yarn start --silent &
  
script:
  # run unit tests:
  - yarn tests
  # run E2E tests:
  - $(npm bin)/cypress run --record